name: agorbns
channels:
  - defaults
  - bioconda
  - conda-forge
  - r
dependencies:
  - python>=3.8
  - sra-tools=2.10.7
  - r-base
  # Add any specific R packages you use with prefix r-
  # Add any specific Python packages you use